#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
#yabai -m config top_padding                  3
#yabai -m config bottom_padding               3
#yabai -m config left_padding                 3
#yabai -m config right_padding                3
yabai -m config window_gap                   5

# Web browsers
yabai -m rule --add app="^Google Chrome|Firefox$" space=1

# apps to not manage (ignore)
app_titles = "^(System Preferences|System Settings)$"
yabai -m rule -add app="${app_titles}" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^App Store$" manage=off

yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Logi Options+$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add title="^Reminders$" manage=off
yabai -m rule --add title="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^CCleaner$" manage=off
yabai -m rule --add app="^GitHub Desktop$" manage=off

#partialy managed
jetbrains_apps="JetBrains Rider"
#yabai -m rule --add app="${jetbrains_apps}" manage=off
#yabai -m rule --add app="${jetbrains_apps}" title=".*\[(.*)\].*" manage=on
#yabai -m rule --add app="^JetBrains Rider" manage=off
#yabai -m rule --add app="^JetBrains Rider" title=".*\[(.*)\].*" manage=on
yabai -m rule --add app="^JetBrains Rider" title='.*Welcome*.|Checkout*.|.*Configurations|Choose*.|Import*.|.*Charges|Tip*.|Rename*.|History for*.|Push Commits to*.|Create New Branch*.|Create:*.|Add File to Git*.|Rollback*.|Move to*.|Change Signature*.|Conflicts*.|Update Project*.|Generate*.|Line Separators Warnings*.|Commit:*.|Merge Revisions for*.' manage=off

#Actions
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"


yabai -m signal --add label=stack_same_name_applications event=window_created action="bash ~/.config/yabai/stack_same_applications.zsh"

echo "yabai configuration loaded.."
